---
- name: Basic GPU Node Setup
  hosts: gpu_nodes
  become: yes

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run NGINX in Docker
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"

    - name: Install htop for system monitoring
      apt:
        name: htop
        state: present

    - name: Run Node Exporter (for Prometheus)
      community.docker.docker_container:
        name: node-exporter
        image: prom/node-exporter
        state: started
        ports:
          - "9100:9100"

    - name: Create Prometheus config directory
      file:
        path: /opt/prometheus
        state: directory

    - name: Copy Prometheus config file
      copy:
        dest: /opt/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ['localhost:9100']

    - name: Run Prometheus (metrics aggregation)
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        ports:
          - "9090:9090"
        volumes:
          - /opt/prometheus:/etc/prometheus
        command: >
          --config.file=/etc/prometheus/prometheus.yml

    - name: Run Grafana dashboard (metrics visualization)
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana-oss
        state: started
        ports:
          - "3000:3000"

    - name: Run Jupyter Notebook (data science environment)
      community.docker.docker_container:
        name: jupyter
        image: jupyter/base-notebook
        state: started
        ports:
          - "8888:8888"
        command: "start-notebook.sh --NotebookApp.token=''"

    - name: Create a non-root admin user
      user:
        name: ansibleadmin
        comment: "Ansible managed admin"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
        create_home: yes

    - name: Set authorized SSH key for ansibleadmin
      authorized_key:
        user: ansibleadmin
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Install ufw (firewall)
      apt:
        name: ufw
        state: present

    - name: Allow required ports through the firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 22
        - 80
        - 9100
        - 8888
        - 9090
        - 3000

    - name: Enable the firewall
      ufw:
        state: enabled
        policy: allow
